# Generated by Django 4.2.16 on 2024-09-19 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
        ('course', '0001_initial'),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='assigned_classrooms',
            field=models.ManyToManyField(related_name='classes_assigned', to='classroom.classroom'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='courses',
            field=models.ManyToManyField(related_name='courses', to='course.course'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='hire_date',
            field=models.DateField(default='2000-01-01'),
        ),
    ]
