# Generated by Django 4.2.16 on 2024-09-19 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_teacher_assigned_classrooms_teacher_courses_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='assigned_classrooms',
        ),
    ]
