# Generated by Django 5.0.6 on 2024-07-17 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classroom', '0001_initial'),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=30)),
                ('course_code', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('department', models.CharField(max_length=20)),
                ('max_capacity', models.PositiveIntegerField()),
                ('pass_grade', models.CharField(max_length=10)),
                ('requirement', models.TextField()),
                ('language', models.TextField()),
                ('schedule', models.DateTimeField()),
                ('classes', models.ManyToManyField(related_name='courses', to='classroom.classroom')),
                ('trainer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course', to='teacher.teacher')),
            ],
        ),
    ]
