# Generated by Django 4.2.16 on 2024-09-19 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='classes',
        ),
    ]
