# Generated by Django 5.0.6 on 2024-07-17 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=20)),
                ('class_code', models.CharField(max_length=10)),
                ('max_students', models.PositiveIntegerField()),
                ('current_students', models.PositiveBigIntegerField()),
                ('no_of_tables', models.PositiveIntegerField()),
                ('no_of_groups', models.PositiveIntegerField()),
                ('room_number', models.CharField(max_length=10)),
                ('class_rep', models.CharField(max_length=20)),
                ('assistant_trainer_incharge', models.CharField(max_length=20)),
                ('no_of_seats', models.PositiveIntegerField()),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='teacher.teacher')),
            ],
        ),
    ]
